- name: Ensure openssh-server is installed
  ansible.builtin.apt:
    name: openssh-server=1:9.2p1-2+deb12u3
    state: present

- name: Start and enable ssh deamon
  ansible.builtin.systemd_service:
    name: sshd
    state: started
    enabled: true
    masked: no

- name: Copy new ssh config
  ansible.builtin.copy:
    src: sshd_config
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: 0644

- name: Reload sshd
  ansible.builtin.systemd_service:
    state: reloaded
    name: sshd

- name: Apply user specific tasks
  ansible.builtin.include_tasks: 
    file: brick_ssh.yml
    apply:
      tags: 
        - brick_ssh