version: '3.8'

services:
  brick:
    image: brick:latest
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 3
    ports:
      - 8000:8000
    environment:
      - UUID="{{.Task.Slot}}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/hostname"]
      retries: 3
      timeout: 5s
      interval: 10s
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
